language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarm build
deploy:
  provider: pages
  edge : true,
  skip-cleanup : true
  keep-history : true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-brach: gh-pages
  commit_messege: "Deploy Release"        
  on:
    branch: master
